CREATE TABLE todos (
    id UUID PRIMARY KEY,
    text TEXT NOT NULL,
    done BOOLEAN NOT NULL,
    user_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 途中でdeleted_atカラムを追加した
ALTER TABLE todos
ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
